// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "Home": {
        "title": "Home",
        "description": "Welcome to the home page of our application. Here you can find the latest updates and features."
    }
};
export default messages;